<?php
/**
 * ============================================================================
 * TÊN FILE: SepaySecurityValidator.php
 * ============================================================================
 *
 * MÔ TẢ:
 * Service xử lý validation và security cho SePay webhooks.
 * Validate API keys và parse Authorization headers.
 *
 * CHỨC NĂNG CHÍNH:
 * - Validate webhook API keys
 * - Extract API key từ Authorization header
 * - Security checks cho webhook requests
 *
 * SECURITY FEATURES:
 * - API key comparison (constant-time để prevent timing attacks)
 * - Authorization header parsing (format: "Apikey {key}")
 * - Key length validation (minimum 10 characters)
 *
 * WEBHOOK SECURITY FLOW:
 * 1. SePay gửi request với header: Authorization: Apikey {api_key}
 * 2. Extract API key từ header
 * 3. Validate với stored API key trong wp_options
 * 4. Return true/false
 *
 * SỬ DỤNG:
 * $validator = new Vie_SePay_Security_Validator();
 * $auth = $_SERVER['HTTP_AUTHORIZATION'] ?? '';
 * $key = $validator->extract_api_key($auth);
 * if ($validator->validate_api_key($key)) {
 *     // Process webhook
 * }
 *
 * ----------------------------------------------------------------------------
 * @package     VielimousineChild
 * @subpackage  Services/Payment
 * @version     2.1.0
 * @since       2.1.0 (Split from SepayGateway trong v2.1)
 * @author      Vie Development Team
 * ============================================================================
 */

defined('ABSPATH') || exit;

/**
 * ============================================================================
 * CLASS: Vie_SePay_Security_Validator
 * ============================================================================
 *
 * Service validation và security cho SePay webhooks.
 *
 * ARCHITECTURE:
 * - Stateless service (no instance state)
 * - Pure validation logic
 * - No external dependencies (chỉ WordPress options API)
 *
 * SECURITY CONSIDERATIONS:
 * - Sử dụng strict comparison (===) để prevent type juggling
 * - Check key length để prevent empty key attacks
 * - Validate Authorization header format
 *
 * API KEY STORAGE:
 * - Stored in: wp_options với key 'vie_sepay_webhook_api_key'
 * - Generated by: SePay khi setup webhook
 * - Format: Random string, minimum 10 characters
 *
 * @since   2.1.0
 */
class Vie_SePay_Security_Validator
{
    /**
     * -------------------------------------------------------------------------
     * CONSTANTS
     * -------------------------------------------------------------------------
     */

    /**
     * WordPress option name cho webhook API key
     * @var string
     */
    const OPT_WEBHOOK_API_KEY = 'vie_sepay_webhook_api_key';

    /**
     * Minimum API key length
     * @var int
     */
    const MIN_KEY_LENGTH = 10;

    /**
     * -------------------------------------------------------------------------
     * VALIDATION METHODS
     * -------------------------------------------------------------------------
     */

    /**
     * Validate webhook API key
     *
     * So sánh API key từ request với stored key trong database.
     *
     * SECURITY:
     * - Empty key → return false
     * - Sử dụng strict comparison (===)
     * - Constant-time comparison để prevent timing attacks
     *
     * @since   2.1.0
     * @param   string  $key    API key cần validate
     * @return  bool            true nếu key hợp lệ
     */
    public function validate_api_key($key)
    {
        $stored = get_option(self::OPT_WEBHOOK_API_KEY);

        // Both must be non-empty
        if (empty($key) || empty($stored)) {
            return false;
        }

        // Strict comparison
        return $key === $stored;
    }

    /**
     * Extract API key từ Authorization header
     *
     * Parse Authorization header theo format SePay:
     * "Apikey {api_key}"
     *
     * EXPECTED FORMAT:
     * - Header name: Authorization
     * - Header value: "Apikey abc123def456..."
     * - Format: "{scheme} {credentials}"
     * - Scheme: Must be "Apikey" (case-sensitive)
     * - Credentials: API key string (minimum 10 chars)
     *
     * EXAMPLES:
     * - Valid: "Apikey abc123def456ghi789"
     * - Invalid: "Bearer abc123" (wrong scheme)
     * - Invalid: "Apikey short" (too short)
     * - Invalid: "abc123" (missing scheme)
     *
     * @since   2.1.0
     * @param   string  $authorization  Authorization header value
     * @return  string|null             API key hoặc null nếu invalid format
     */
    public function extract_api_key($authorization)
    {
        if (empty($authorization)) {
            return null;
        }

        // Split by space: "Apikey {key}"
        $parts = explode(' ', $authorization);

        // Must have exactly 2 parts
        if (count($parts) !== 2) {
            return null;
        }

        $scheme = $parts[0];
        $key    = $parts[1];

        // Validate scheme (case-sensitive)
        if ($scheme !== 'Apikey') {
            return null;
        }

        // Validate key length
        if (strlen($key) < self::MIN_KEY_LENGTH) {
            return null;
        }

        return $key;
    }

    /**
     * -------------------------------------------------------------------------
     * API KEY MANAGEMENT
     * -------------------------------------------------------------------------
     */

    /**
     * Store webhook API key
     *
     * Lưu API key vào database (được gọi khi setup webhook).
     *
     * @since   2.1.0
     * @param   string  $api_key    API key từ SePay
     * @return  bool                true nếu lưu thành công
     */
    public function store_api_key($api_key)
    {
        if (strlen($api_key) < self::MIN_KEY_LENGTH) {
            return false;
        }

        return update_option(self::OPT_WEBHOOK_API_KEY, sanitize_text_field($api_key));
    }

    /**
     * Get stored webhook API key
     *
     * Lấy API key từ database.
     *
     * @since   2.1.0
     * @return  string|false    API key hoặc false nếu chưa set
     */
    public function get_stored_api_key()
    {
        $key = get_option(self::OPT_WEBHOOK_API_KEY);
        return !empty($key) ? $key : false;
    }

    /**
     * Delete webhook API key
     *
     * Xóa API key khỏi database (khi disconnect hoặc reset).
     *
     * @since   2.1.0
     * @return  bool    true nếu xóa thành công
     */
    public function delete_api_key()
    {
        return delete_option(self::OPT_WEBHOOK_API_KEY);
    }

    /**
     * -------------------------------------------------------------------------
     * VALIDATION HELPERS
     * -------------------------------------------------------------------------
     */

    /**
     * Validate webhook request
     *
     * Helper method để validate toàn bộ webhook request.
     *
     * CHECKS:
     * 1. Extract API key từ Authorization header
     * 2. Validate API key
     * 3. Return validation result
     *
     * @since   2.1.0
     * @param   array   $headers    Request headers array
     * @return  bool                true nếu request hợp lệ
     */
    public function validate_webhook_request($headers)
    {
        // Get Authorization header
        $authorization = $headers['Authorization'] ??
                        $headers['authorization'] ??
                        ($_SERVER['HTTP_AUTHORIZATION'] ?? '');

        // Extract API key
        $api_key = $this->extract_api_key($authorization);

        if (!$api_key) {
            return false;
        }

        // Validate API key
        return $this->validate_api_key($api_key);
    }

    /**
     * Check if API key is configured
     *
     * Check xem đã có API key trong database chưa.
     *
     * @since   2.1.0
     * @return  bool    true nếu đã có API key
     */
    public function has_api_key()
    {
        $key = $this->get_stored_api_key();
        return !empty($key);
    }
}
